// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loadingScreenBackdrop': string;
}
export const cssExports: CssExports;
export default cssExports;
