// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomSideContainer': string;
  'chartContainer': string;
  'lessonsLegendsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
