// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropdownHeroItem': string;
  'dropdownSelectorContainer': string;
  'label': string;
  'openedArrow': string;
  'option': string;
  'optionsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
