// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cardContainer': string;
  'toggleBullet': string;
  'toggleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
