// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'campNameTitle': string;
  'legendsContainer': string;
  'schoolsLegendContainer': string;
  'totalTitle': string;
  'totalTitleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
